### ISSUE TITLE
Editoast: add search endpoint

### ISSUE THREAD

**Issue by alexandredamiron** [alexandredamiron/osrd-fork#1777]
Adds the `/search?<page>&<page_size>` endpoint.

Example payload:

```json
{
    "object": "operationalpoint",
    "query": ["or", 
                ["search", ["name"], "marse"], 
                ["=", ["trigram"], "pno"]],
}
```

The endpoint is generic enough so that new types of objects can be searched without modifying the route. For example, when we'll add signals into the search engine, we will
create a table named `osrd_search_signal` with some columns (e.g.: "label", "aspect", etc.). Then we'll update `search.yml` like so:

```yaml
operationalpoint: ...
...
signal:
  table: osrd_search_signal
  columns:
    label: string
    aspect: string
    ...
  result:
    joins: ...
    columns:
      obj_id: obj_id
      infra_id: infra_id
      label: data#>>'{extensions,identifier,label}'
      aspect: data#>>'{extensions,identifier,aspect}'
      ...
```

We will then be able to query the route like this without changing the route's logic:

```json
{
    "object": "signal",
    "query": ["and", 
                ["search", ["label"], "C14"], 
                ["=", ["aspect"], "carre"]
                ["=", ["infra_id"], 2]],
}
```

Only implemented for operational points for now.

See also #3002 
Fixes #1625, fixes #1635
